//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericaVirtual.WebAPI.Persistance.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherConditions
    {
        public int Id { get; set; }
        public int IdCity { get; set; }
        public int IdDay { get; set; }
        public int IdWeather { get; set; }
        public int TemperatureCelsius { get; set; }
        public int Precipitation { get; set; }
        public int Humidity { get; set; }
        public int Wind { get; set; }
        public decimal TemperatureFahrenheit { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Days Days { get; set; }
        public virtual Weathers Weathers { get; set; }
    }
}
